sudo: required
services:
  - docker

before_install:
  - docker build -t petersenrex/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true petersenrex/react-test npm run test

after_success:
  - docker build -t petersenrex/multi-client ./client
  - docker build -t petersenrex/multi-nginx ./nginx
  - docker build -t petersenrex/multi-server ./server
  - docker build -t petersenrex/multi-worker ./worker
  # docker hub login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push petersenrex/multi-client
  - docker push petersenrex/multi-nginx
  - docker push petersenrex/multi-server
  - docker push petersenrex/multi-worker  

#deploy:
#  edge: true
#  provider: elasticbeanstalk
#  region: "us-east-1"
#  app: "multi-docker"
#  env: "MultiDocker-env"
#  bucket_name: "elasticbeanstalk-us-east-1-360803683024"
#  bucket_path: "multi-docker"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: "$AWS_SECRET_KEY"
#
